### ISSUE TITLE
关于“/orders{?market,limit}”的疑问

### ISSUE THREAD

**Issue by jackalxx1** [inblockchain/bigone-developer-api#1]
https://api.big.one/orders?market=ETH-BTC&limit=10

这个get的是什么信息？我试过我交易过的market，返回的信息都是空的

**Comment by jackalxx1** [comment]
其实我想开发一个小应用，需要查询每天自己成交的是否达到20单，好像没相关的接口可以实现这个功能？

**Comment by tooooolong** [comment]
你说的应该是

https://developer.big.one/#order-orders-get

这个接口吧？

目前开放接口正在迭代，所以文档和实现有些不同步
这个接口有一个隐藏参数 `state` 取值范围是：'', 'open', 'done'

默认是‘open’ 就是返回所有还未成交或全部成交的交易，
done则返回取消或者成交的交易。

所以按照你的需求，query string 中 带上state=done就可以查询到是否有20单交易。

```
https://api.big.one/orders?market=ETH-BTC&limit=10&state=done
```

**Comment by tooooolong** [comment]
feel free to reopen this issue

**Comment by jackalxx1** [comment]
谢谢，已经实现我要的功能。后来我使用的是“https://api.big.one/trades?market=ETH-BTC”，按交易时间统计笔数。

有点小疑问，api返回的是格林尼治时间，而新年糖果活动的时间应该是东八区时间，但中文公告没注明，并且英文公告只是直接翻译，沿用了东八区时间
