### ISSUE TITLE
为什么 PXN OpenAPI 的文档要放在这个 repo 里?

### ISSUE THREAD

**Issue by xieyuheng** [inblockchain/bigone-developer-api#2]

**Comment by xieyuheng** [comment]
https://github.com/inblockchain/bigone-developer-api/blob/master/swagger/openapi.yml

**Comment by tooooolong** [comment]
@xieyuheng 当时图方便直接丢进来了，你可以搞一个放文档的地方，从这儿移出去

**Comment by xieyuheng** [comment]
那就先用这个 repo, 我 pr 这个.
